### ISSUE TITLE
Krunner_bridge shared libary not found fix

### ISSUE THREAD

**Issue by alex1701c** [Shihira/krunner-bridge#2]
Hello,

I got the error 

> Error loading plugin "krunner_bridge" "The shared library was not found."

It can be fixed by copying the krunner_bridge.so  library (~/.local/lib/qt/plugins/krunner_bridge.so) to /usr/lib/x86_64-linux-gnu/qt5/plugins/. 

Alternatively you can set the plugin path: 
export `QT_PLUGIN_PATH="~/.local/lib/qt/plugins/"`

Furthermore I had to change the Python-version to python3, otherwise it throws syntax errors.

Maybe you want to add these bug-fixes to your README 🙃.

PS: I am running Kubuntu 18.04 with KDE Plasma 5.12.7 and Qt 5.9.5.

**Comment by danielatdattrixdotcom** [comment]
Running vanilla Gentoo here. I added the home QT_PLUGIN_PATH to **.bashrc** and all was well. Adding to the README would be helpful I'm sure.

**Comment by Shihira** [comment]
Thank you both for reporting. Have added it to the FAQ section.
